#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../core/mode-config.sh"
source "$SCRIPT_DIR/../external-ca/contract.sh"

replace_exact_line_with_block() {
  local file_path="$1"
  local placeholder_line="$2"
  local block_text="$3"
  local line
  while IFS= read -r line; do
    if [[ "$line" == "$placeholder_line" ]]; then
      printf '%s\n' "$block_text"
    else
      printf '%s\n' "$line"
    fi
  done < "$file_path"
}

render_mode_manifest() {
  local mode="$1"
  local out_file="$2"
  local namespace="${3:-default}"
  local templates_dir="$POC_DIR/manifests/templates"
  local base_fragment="$templates_dir/cluster-base.yaml"
  local self_overlay="$templates_dir/self-signed-overlay.yaml"
  local external_overlay="$templates_dir/external-ca-overlay.yaml"

  local endpoint_block=""
  local kcp_files_block=""
  local overlay_tmp worker_template_name external_files_secret

  mode_config "$mode"
  worker_template_name="${MODE_CFG_CLUSTER_NAME%-cluster}-worker"
  external_files_secret="${MODE_CFG_CLUSTER_NAME}-external-ca-files"

  if [[ ! -s "$base_fragment" ]]; then
    echo "missing base manifest fragment: $base_fragment" >&2
    return 1
  fi

  if [[ "$mode" == "external-ca" ]]; then
    endpoint_block=$(cat <<EOB
  controlPlaneEndpoint:
    host: ${MODE_CFG_CLUSTER_NAME}-lb
    port: 6443
EOB
)
    kcp_files_block="$(external_ca_contract_kcp_files_yaml "$external_files_secret")"
    overlay_tmp="$(mktemp)"
    replace_exact_line_with_block "$external_overlay" "__KCP_FILES_BLOCK__" "$kcp_files_block" > "$overlay_tmp"
  else
    overlay_tmp="$(mktemp)"
    cat "$self_overlay" > "$overlay_tmp"
  fi

  mkdir -p "$(dirname "$out_file")"
  {
    echo "# Generated by hack/scripts/helpers/render/manifests.sh. Do not edit by hand."
    replace_exact_line_with_block "$base_fragment" "__CONTROL_PLANE_ENDPOINT_BLOCK__" "$endpoint_block"
    cat "$overlay_tmp"
  } | sed \
    -e "s|__CLUSTER_NAME__|${MODE_CFG_CLUSTER_NAME}|g" \
    -e "s|__KCP_NAME__|${MODE_CFG_KCP_NAME}|g" \
    -e "s|__WORKER_MD_NAME__|${MODE_CFG_WORKER_MD_NAME}|g" \
    -e "s|__WORKER_TEMPLATE_NAME__|${worker_template_name}|g" \
    -e "s|__NAMESPACE__|${namespace}|g" \
    -e "s|__EXTERNAL_CA_FILES_SECRET_NAME__|${external_files_secret}|g" \
    > "$out_file"

  rm -f "$overlay_tmp"
}
